version: '3'

services:
  limesurvey:
    image: acspri/limesurvey:latest
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
    volumes:
      - limesurvey-plugins:/var/www/html/plugins
      - limesurvey-upload:/var/www/html/upload
      - limesurvey-config:/var/www/html/application/config

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  limesurvey-plugins:
  limesurvey-upload:
  limesurvey-config:
  mysql-data: